# Generated by Django 3.2.5 on 2021-07-19 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilingParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('province', models.CharField(choices=[('Alberta', 'Alberta'), ('British Columbia', 'British Columbia'), ('Manitoba', 'Manitoba'), ('New Brunswick', 'New Brunswick'), ('Newfoundland and Labrador', 'Newfoundland and Labrador'), ('Nova Scotia', 'Nova Scotia'), ('Nunavut', 'Nunavut'), ('Ontario', 'Ontario'), ('Quebec', 'Quebec'), ('Saskatchewan', 'Saskatchewan')], max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('registry_office', models.CharField(choices=[('Calgary', 'Calgary'), ('Charlottetown', 'Charlottetown'), ('Edmonton', 'Edmonton'), ('Fredericton', 'Fredericton'), ('Halifax', 'Halifax'), ('Iqaluit', 'Iqaluit'), ('Montreal', 'Montreal'), ('Ottowa', 'Ottowa'), ('Quebec', 'Quebec'), ('Regina', 'Regina'), ('Saint John', 'Saint John'), ('Saskatoon', 'Saskatoon'), ("St. John's", "St. John's"), ('Toronto', 'Toronto'), ('Vancouver', 'Vancouver'), ('Whitehorse', 'Whitehorse'), ('Winnipeg', 'Winnipeg'), ('Yellowknife', 'Yellowknife')], max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(max_length=200)),
                ('client_last_name', models.CharField(max_length=200)),
                ('appeal_type', models.CharField(choices=[('RPD', 'RPD'), ('RAD', 'RAD'), ('H&C', 'H&C'), ('PRRA', 'PRRA'), ('Deferral', 'Deferral'), ('SP', 'SP'), ('TRV', 'TRV')], max_length=200)),
                ('submission_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('due_date', models.DateTimeField(null=True)),
                ('secondary_email', models.EmailField(max_length=200, null=True)),
                ('confirmation_number', models.CharField(max_length=200, null=True)),
                ('filing_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jr_notice.filingparty')),
            ],
        ),
    ]
