# Generated by Django 3.2.5 on 2021-07-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jr_notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filingparty',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('French', 'French')], max_length=200),
        ),
    ]
