# Generated by Django 3.2.5 on 2021-07-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jr_notice', '0002_alter_filingparty_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submissions',
            new_name='Submission',
        ),
        migrations.AlterField(
            model_name='filingparty',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('French', 'French')], max_length=15),
        ),
    ]
