# Generated by Django 3.2.5 on 2021-07-22 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jr_notice', '0004_auto_20210721_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filingparty',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='submission',
            name='filing_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jr_notice.filingparty'),
        ),
    ]
