# Generated by Django 3.2.5 on 2021-07-22 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jr_notice', '0005_auto_20210722_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='filing_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jr_notice.filingparty'),
        ),
    ]
