# Generated by Django 3.2.5 on 2021-07-25 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jr_notice', '0006_alter_submission_filing_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.TextField()),
                ('last_names', models.TextField()),
                ('number_of_applicants', models.IntegerField()),
                ('app_type', models.CharField(max_length=20)),
                ('decision_maker', models.CharField(max_length=255)),
                ('sec_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('scan_errors', models.TextField()),
                ('file_size', models.CharField(max_length=200)),
                ('file_content', models.CharField(max_length=200)),
                ('filing_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jr_notice.filingparty')),
            ],
        ),
    ]
