# Generated by Django 3.2.5 on 2021-07-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jr_notice', '0007_clientinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientInfo',
            new_name='ScanResult',
        ),
    ]
