# Generated by Django 3.2.5 on 2021-07-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jr_notice', '0008_rename_clientinfo_scanresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='date_scanned',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
