# Generated by Django 3.2.5 on 2021-07-25 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jr_notice', '0009_scanresult_date_scanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_date_db',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='due_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TimeTook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_took', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jr_notice.submission')),
            ],
        ),
    ]
