# Generated by Django 3.2.5 on 2021-07-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jr_notice', '0010_auto_20210725_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='first_names',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='last_names',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='number_of_applicants',
            field=models.IntegerField(null=True),
        ),
    ]
