# Generated by Django 3.2.5 on 2021-07-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jr_notice', '0011_auto_20210726_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='app_type',
            field=models.CharField(choices=[('RPD', 'RPD'), ('RAD', 'RAD'), ('H&C', 'H&C'), ('PRRA', 'PRRA'), ('Deferral', 'Deferral'), ('SP', 'SP'), ('TRV', 'TRV')], max_length=20),
        ),
    ]
