# Generated by Django 3.2.5 on 2021-07-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jr_notice', '0012_alter_scanresult_app_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='file_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
