# Generated by Django 3.2.5 on 2021-07-28 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jr_notice', '0013_scanresult_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='filing_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jr_notice.filingparty'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='number_of_applicants',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='filing_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jr_notice.filingparty'),
        ),
        migrations.AlterField(
            model_name='timetook',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jr_notice.submission'),
        ),
    ]
