# Generated by Django 3.2.5 on 2021-07-28 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jr_notice', '0014_auto_20210727_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filingparty',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='filing_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jr_notice.filingparty'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='filing_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jr_notice.filingparty'),
        ),
        migrations.AlterField(
            model_name='timetook',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jr_notice.submission'),
        ),
    ]
