# Generated by Django 3.2.5 on 2021-07-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jr_notice', '0015_auto_20210727_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='number_of_applicants',
            field=models.IntegerField(null=True),
        ),
    ]
